source "http://rubygems.org"
gem "sinatra"
gem "activerecord"
gem "haml"
gem "mongo"
gem "mongoid"
gem "pusher"
gem "bson_ext"
gem "omniauth"
gem "omniauth-twitter"
gem "omniauth-google-oauth2"
gem "omniauth-dropbox"
gem "dropbox-sdk"
gem "coffee-script", "~> 2.2.0"
gem "sprockets", "~> 2.0"
